# Change these first
owner: GabrielDom # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: DMP v4 (Login)
    url: https://dmp.retargetly.com/auth/login
    # method: POST
    # headers:
    # - "Content-Type: application/json"
    # body: '{username: "gabriel.dominguez@retargetly.com", password: "Gaby38826900!"}'
    maxResponseTime: 6000
  - name: DMP v3
    url: https://dmpv3.retargetly.com/
  - name: Loop
    url: https://loop.retargetly.com/
  - name: Google
    url: https://www.google.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
    
assignees:
  - GabrielDom
  - charlie-rely
  - guamacherox

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status monitor for DMP suite
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/GabrielDom/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
